# Generated by Django 4.2.8 on 2024-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.CharField(default=1, max_length=10000000),
            preserve_default=False,
        ),
    ]
