# Generated by Django 4.2.8 on 2024-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0002_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
