# Generated by Django 5.0.1 on 2024-01-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sellers', '0003_alter_recipt_order'),
        ('Sellers', '0004_alter_log_date'),
    ]

    operations = [
    ]
