# Generated by Django 4.2 on 2024-01-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="recipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Not_paid", "Not paid"),
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                        ],
                        default="Pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("serial_no", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Sellers.order",
                    ),
                ),
            ],
        ),
    ]
