# Generated by Django 4.2.5 on 2023-09-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_id', models.CharField(max_length=11)),
                ('item_order_id', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=11)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('open_status', models.BooleanField(default=True)),
                ('waiting_status', models.BooleanField(default=False)),
                ('send_status', models.BooleanField(default=False)),
                ('close_status', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='order.orderitem')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
