# Generated by Django 4.2.5 on 2023-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
    ]
