# Generated by Django 4.2.5 on 2023-10-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_orderitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
    ]
