# Generated by Django 4.2 on 2023-10-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0004_remove_order_item_orderitem_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="item", new_name="product",
        ),
        migrations.RemoveField(model_name="orderitem", name="cost",),
    ]
