# Generated by Django 4.2 on 2023-10-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0006_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="open", field=models.BooleanField(default=False),
        ),
    ]
