# Generated by Django 4.2 on 2023-10-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0007_order_open"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="open",),
    ]
