# Generated by Django 4.2 on 2023-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Seller", "0008_remove_order_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="active", field=models.BooleanField(default=False),
        ),
    ]
